remote_theme: pages-themes/primer@v0.6.0
baseurl: "/tc-wiki"
url: cosimoquiche.github.io
markdown: kramdown
title: null
name: ""

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true