remote_theme: Drassil/git-wiki-theme@master
baseurl: "/tc-wiki"
url: cosimoquiche.github.io
markdown: kramdown

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true